- src/ts/message.ts
- test/proto/examplecom/primitive_message_v2.proto
- test/proto/examplecom/primitive_message_v3.proto
- test/ts_test/generate.sh
- test/ts_test/package.json
- test/ts_test/src/maps.ts
- test/ts_test/src/primitivesV2.ts
- test/ts_test/src/primitivesV3.ts
This fixes #2 as well as updating tests so `npm test` passes on travis again.
> Fix travis build and emit canonical name for capitalized proto fields in messages.

- src/ExportMap.ts
- test/proto/orphan.proto
- test/ts_test/src/maps.ts
This fixes the generation of exported names from file descriptors that do not have a package - #10
> Fixes #10 - Messages without packages

- src/ts/fileDescriptorTSServices.ts
- test/proto/examplecom/simple_service.proto
- test/ts_test/src/service.ts
I got burnt by https://github.com/improbable-eng/ts-protoc-gen/issues/25 too so thought I'd have a go at fixing it.
Will also have a go at adding some tests for this.
@linlexing @MarcusLongmuir
> Don't output variables that are not used in typescript service definition

- package-lock.json
- package.json
* Addresses a deprecation warning during `npm install`
* Adds `package-lock`
> Migrate from deprecated babel to babel-cli package

- bin/BUILD
- src/BUILD
- Remove reference to `protoc-gen-js_service` binary which was removed in #44
- Remove `js/*.ts` source path which was removed in #44
> Tidy up Bazel build

- src/index.ts
- src/service/grpcweb.ts
- src/ts/fileDescriptorTSD.ts
- src/util.ts
- test/ts_test/src/util.ts
This PR fixes a bug which occurs for users storing their `proto` definitions inside a `.proto` directory.
The bug is caused by `filePathFromProtoWithoutExtension` replacing all occurrences of `.proto` when renaming a file instead of just the file suffix.
A drive-by improvement to the documentation of ts-protoc-gen entry point.
> Fix replace all bug in filePathFromProtoWithoutExtension

- README.md
Updated README so that bazel instructions are correct:
* there has to be a gir_repository in WORKSPACE so that ts-protoc-gen reference can be resolved
* there was a duplicate rule in BUILD which is completely redundant
> README update: add git repo for ts_protoc_gen and remove rule duplicate

- README.md
The Bazel instructions are lengthy and only appeal to a subset of users, hiding them behind a `<details>` tag seems like a sensible solution
> Collapse Bazel Instructions in README

- README.md
Hint that the path to ts-protoc-gen must be absolute on Windows. Fixes #100
> Add hint for Windows users

- examples/generated/proto/examplecom/simple_service_pb_service.d.ts
- examples/generated/proto/orphan_pb_service.d.ts
- src/service/grpcweb.ts
- test/integration/service/grpcweb.ts
[`ServiceError`'s can be `null`](https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/service/grpcweb.ts#L342), but the TypeScript type doesn't reflect that. This just updates the type declaration for `ServiceError`.
> Make ServiceError optionally null

- generate.sh
- package-lock.json
- travis-ci-build.sh
Add a travis build step which re-generates the generated code and then checks for changes to the workspce. If any are detected it will fail the build and prompt the user to run the `./generate.sh` script.
> CI should check that generated code has been committed

- examples/generated/proto/examplecom/simple_service_pb_service.d.ts
- examples/generated/proto/orphan_pb_service.d.ts
- src/service/grpcweb.ts
What the title says. Should be good, given that clients are initialized with...
```
function BookServiceClient(serviceHost, options) {
this.serviceHost = serviceHost;
this.options = options || {};
}
```
> Transport member of ServiceClientOptions should be optional

- examples/generated/proto/examplecom/simple_service_pb_service.d.ts
- examples/generated/proto/orphan_pb_service.d.ts
- src/service/grpcweb.ts
- test/integration/service/grpcweb.ts
It appears we were using the responseType instead of the requestType when creating the stream.
Fixes #132, #133
> Correct generated client, bidi stream method stubs

- examples/generated/proto/examplecom/simple_service_pb_service.d.ts
- examples/generated/proto/orphan_pb_service.d.ts
- package-lock.json
- package.json
- src/service/grpcweb.ts
- test/helpers/fakeGrpcTransport.ts
- test/integration/service/grpcweb.ts
- change signature on Service Stubs to expect `grpc.Transport` interface
- Patch up `fakeGrpcTransport` to use the publically exported interfaces
> Upgrade grpc-web-client to 0.7.0

- examples/generated/proto/examplecom/simple_service_pb_service.d.ts
- examples/generated/proto/examplecom/simple_service_pb_service.js
- examples/generated/proto/orphan_pb_service.d.ts
- examples/generated/proto/orphan_pb_service.js
- src/service/grpcweb.ts
- test/integration/service/grpcweb.ts
implemented changes specified in #155 
There were 4 tests that broke with this change because they were explicitly expecting `onEnd` to come before `onStatus`, so I updated those. I also wrote 4 new tests to ensure that the `onEnd` handler is called with a status and that that status matches the one returned from `onStatus`.
> Swap onStatus to invoke BEFORE onEnd rather than after

- examples/generated/proto/examplecom/enum_message_pb.d.ts
- examples/generated/proto/examplecom/map_message_pb.d.ts
- examples/generated/proto/orphan_pb.d.ts
- examples/generated/proto/othercom/external_enum_pb.d.ts
- src/ts/FieldTypes.ts
- src/ts/enum.ts
- src/ts/message.ts
- test/integration/maps.ts
More detail in: https://github.com/improbable-eng/ts-protoc-gen/issues/156
- This changes how the type generation handles protobuf enums
- Regenerated all examples to run tests against
I checked and there seem to be a fair few tests for enum handling, the code changes are backwards compatible so they were not modified. Not sure if there are any additional tests worth writing? I did however have to change some of the casting in the integration test for maps - not sure if the changes makes sense though 🤔
> Handling of enums

- src/index.ts
`new Buffer()` is deprecated, use `Buffer.from()` instead.
Fixes #164
> Replace deprecated `new Buffer()` with `Buffer.from()`

- README.md
Adds instructions to the bazel section on how to enable code completion for generated files.
> bazel IntelliJ Code Completion Instructions

- .travis.yml
- BUILD.bazel
- WORKSPACE
- defs.bzl
- package-lock.json
- package.json
- src/BUILD.bazel
- yarn.lock
Updates the bazel rules to be compatible with v26 and updates the rules_nodejs version to the latest. Also renames a `BUILD` file to `BUILD.bazel`.
> Upgrade to bazel 0.26.0

- src/bazel/change_import_style.ts
- test/bazel/BUILD.bazel
- test/bazel/proto/BUILD.bazel
- test/bazel/proto/naming_styles.proto
- test/bazel/test_bundling.ts
Fixes a bug in the bazel rules where names with numbers were not being exported and adds a test.
> Bazel Rules: Messages with Numbers

- CONTRIBUTING.md
Fixing the Code of Conduct link in the Contributing doc.
Clicked the link 🙂
> Fix link to Code of Conduct in Contributing

- examples/generated-grpc-js-node/proto/examplecom/parent_message_v3_pb.d.ts
- examples/generated-grpc-js-node/proto/examplecom/parent_message_v3_pb.js
- examples/generated-grpc-js-node/proto/examplecom/primitive_message_v3_pb.d.ts
- examples/generated-grpc-js-node/proto/examplecom/primitive_message_v3_pb.js
- examples/generated-grpc-node/proto/examplecom/parent_message_v3_pb.d.ts
- examples/generated-grpc-node/proto/examplecom/parent_message_v3_pb.js
- examples/generated-grpc-node/proto/examplecom/primitive_message_v3_pb.d.ts
- examples/generated-grpc-node/proto/examplecom/primitive_message_v3_pb.js
- examples/generated-grpc-web/proto/examplecom/parent_message_v3_pb.d.ts
- examples/generated-grpc-web/proto/examplecom/parent_message_v3_pb.js
- examples/generated-grpc-web/proto/examplecom/primitive_message_v3_pb.d.ts
- examples/generated-grpc-web/proto/examplecom/primitive_message_v3_pb.js
- examples/generated/proto/examplecom/parent_message_v3_pb.d.ts
- examples/generated/proto/examplecom/parent_message_v3_pb.js
- examples/generated/proto/examplecom/primitive_message_v3_pb.d.ts
- examples/generated/proto/examplecom/primitive_message_v3_pb.js
- package-lock.json
- package.json
- proto/examplecom/parent_message_v3.proto
- proto/examplecom/primitive_message_v3.proto
- src/index.ts
- src/ts/message.ts
- test/integration/nestedMessagesV3.ts
- test/integration/primitivesV2.ts
- test/integration/primitivesV3.ts
Add implementation for proto3 optional fields with presence tracking. Spec: https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
Fixes: https://github.com/improbable-eng/ts-protoc-gen/issues/263
Additionally, this change:
- Improves tests for the proto2 scalar messages
- Explicitly calls `.buffer` on the serialized message before passing into `Buffer.from` to handle a weird typescript issue.
Tested via unit tests and visual inspection of generated files.
> Add support for proto3 optional presence

- .travis.yml
- travis-ci-build.sh
* Stopped caching `node_modules` - appears to have negligible impact on CI duration.
* Fixes CI that [appeared to be](https://travis-ci.org/github/improbable-eng/ts-protoc-gen/builds/768112003#L497) hitting a npm issue that [inexplicably downgrades from https to http when `npm install`ing](https://npm.community/t/npm-install-downgrading-resolved-packages-from-https-to-http-registry-in-package-lock-json/1818).
* CI passed for this branch
> Fix CI failing due to diff caused by npm install

- src/ts/extensions.ts
For repeated extension fields add "List" suffix and change type to Array of `fieldType`.
Tested manually on my project.
> Closes improbable-eng/ts-protoc-gen#313 : Support repeated extension fields
